spring:
  mvc:
    #静态资源加访问前缀
    # static-path-pattern: /res/**
    #  自定义静态资源路径
    #  web:
    #    resources:
    #      static-locations: classpath:/haha

    #rest风格的url地址
    hiddenmethod:
      filter:
        enabled: true
